# Image Augmentation parameters
AUGMENTATION : True
RANDOM_FLIP : "vertical"
RANDOM_ROTATION : 0.01
RANDOM_ZOOM : 0.01
RANDOM_CONTRAST : 0.01
RANDOM_BRIGHTNESS: 0.01
# Model Parameters for transfer learning
IMAGE_SIZE: [224,224,3] # as per VGG 16 model
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 100
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.00001
USE_PRETRAINED_MODEL: False
USE_CATEGORICAL_ENCODING: True
USE_TF_DATASET: False
USE_PICKLED_DATA: True