# Image Augmentation parameters
AUGMENTATION : True
RANDOM_FLIP : "horizontal"
RANDOM_ROTATION : 0.05
RANDOM_ZOOM : 0.1
RANDOM_CONTRAST : 0.2
RANDOM_BRIGHTNESS: 0.2
# Model Parameters for transfer learning
IMAGE_SIZE: [224,224,3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 100
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.0000001
USE_PRETRAINED_MODEL: True
USE_CATEGORICAL_ENCODING: True
USE_TF_DATASET: False
USE_PICKLED_DATA: True