# Stage 01 Data Ingestion
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion/.kaggle
  kaggle_source: mohamedhanyyy/chest-ctscan-images


# Stage 02 Base model preparation
prepare_base_model:
  root_dir: artifacts/prepare_base_model/
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras

# Stage 03 Train model
train_model:
  root_dir: artifacts/train_model/
  model_path: artifacts/train_model/model.keras

# Stage 04 Evaluate model
evaluate_model:
  root_dir: artifacts/evaluate_model/