# Stage 01 Data Ingestion
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion/.kaggle
  kaggle_source: mohamedhanyyy/chest-ctscan-images


# Stage 02 Base model preparation
prepare_base_model:
  root_dir: artifacts/prepare_base_model/
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5